### ISSUE TITLE
[Optimisation]: 简化显示内容

### ISSUE THREAD

**Issue by miaoice** [XtremeWave/TownOfNewEpic_XtremeBot#4]
### 联系方式(邮箱)

1480459201@qq.com

### 想优化的内容是什么?

显示内容的通俗？

### 想要优化此内容的什么?

房号 人数 [版本]
服务器
房主

**Comment by QingFeng-awa** [comment]
目前车队姬已经够简洁了,每个东西都有它存在的意义。
并且,您应该知道车队姬每行消息代表的内容是什么 _(换句话来说就是够通俗了)_ 。
> KARPED1EM用于[TownOfHostEdited](https://github.com/KARPED1EM/TownOfNext/tree/TOHE)的车队姬跟我们的车队姬是差不多的。
不过,我们可以考虑删除'房主'这一条信息。
您认为呢?
